/**
 * Created by TOTVS Labs Rest Api to Angular Class Generator
 */

(function () {
    'use strict';

    var tsRestService = require('../fetch.rest.api.js');

    module.exports = tsStagingService(tsRestService);

    function tsStagingService (
        tsRestService
    ) {

        function getStagingEntityById (type, id) {
            return tsRestService.$get('staging/entities/' + type + '/' + id);
        }

        /* queryParams Defaults: applicationId=, isAutoGenerated=true */
        function stagingTypeJsonSchema (type, queryParams) {
            return tsRestService.$get('staging/entities/types/' + type + '/schema', queryParams);
        }

        function createStagingTypeJsonSchema (type, body) {
            return tsRestService.$post('staging/entities/types/' + type + '/schema', body);
        }

        /* queryParams Defaults: entitySpace=PRODUCTION */
        function processStagingDataDryRun (type, body, queryParams) {
            return tsRestService.$post('staging/entities/types/' + type + '/dryRun', body, null, queryParams);
        }

        function processStagingDataSynchronously (type, body) {
            return tsRestService.$post('staging/entities/types/' + type + '/sync', body);
        }

        /* queryParams Defaults: restoreStagingSchema=false, startDate=, endDate= */
        function restoreDocumentsForAllTypes (queryParams) {
            return tsRestService.$post('staging/restore', null, null, queryParams);
        }

        /* queryParams Defaults: sourceAppName=, restoreStagingSchema=false, startDate=, endDate= */
        function restoreDocumentsForStagingType (type, queryParams) {
            return tsRestService.$post('staging/entities/types/' + type + '/restore', null, null, queryParams);
        }

        /* queryParams Defaults: offset=0, pageSize=10, sortBy=mdmId, sortOrder=ASC */
        function searchStagingData (body, queryParams) {
            return tsRestService.$post('staging/search', body, null, queryParams);
        }

        /* queryParams Defaults: returnData=false */
        function sendStagingDataInGzipRFC1952Format (type, body, queryParams) {
            return tsRestService.$post('staging/entities/types/' + type, body, null, queryParams);
        }

        function updateStagingTypeSchema (type, body) {
            return tsRestService.$put('staging/entities/types/' + type + '/schema', body);
        }

        /* queryParams Defaults: deleteRejected=false */
        function deleteDocumentsForStagingType (type, queryParams) {
            return tsRestService.$delete('staging/entities/types/' + type, queryParams);
        }

        return {
            getStagingEntityById: getStagingEntityById,
            stagingTypeJsonSchema: stagingTypeJsonSchema,
            createStagingTypeJsonSchema: createStagingTypeJsonSchema,
            processStagingDataDryRun: processStagingDataDryRun,
            processStagingDataSynchronously: processStagingDataSynchronously,
            restoreDocumentsForAllTypes: restoreDocumentsForAllTypes,
            restoreDocumentsForStagingType: restoreDocumentsForStagingType,
            searchStagingData: searchStagingData,
            sendStagingDataInGzipRFC1952Format: sendStagingDataInGzipRFC1952Format,
            updateStagingTypeSchema: updateStagingTypeSchema,
            deleteDocumentsForStagingType: deleteDocumentsForStagingType
        };
    }

})();
